# Generated by Django 5.2 on 2025-04-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpackage',
            name='has_booked_slot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
