# Generated by Django 5.2 on 2025-04-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentpackage_has_booked_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='time_slot',
            field=models.CharField(choices=[('7:00 AM - 8:30 AM', '7:00 AM - 8:30 AM'), ('9:00 AM - 10:30 AM', '9:00 AM - 10:30 AM'), ('11:00 AM - 12:30 PM', '11:00 AM - 12:30 PM'), ('1:00 PM - 2:30 PM', '1:00 PM - 2:30 PM'), ('3:00 PM - 4:30 PM', '3:00 PM - 4:30 PM'), ('5:00 PM - 6:30 PM', '5:00 PM - 6:30 PM')], max_length=20),
        ),
    ]
