# Generated by Django 5.2 on 2025-04-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_course_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('SCOOTY', 'Scooty'), ('OTHER', 'Other'), ('HEAVY', 'HEAVY'), ('SCOOTY&CAR', 'SCOOTY & CAR')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingpackage',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('SCOOTY', 'Scooty'), ('OTHER', 'Other'), ('HEAVY', 'HEAVY'), ('SCOOTY&CAR', 'SCOOTY & CAR')], max_length=10),
        ),
    ]
