# Generated by Django 5.2 on 2025-04-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('SCOOTY', 'Scooty'), ('OTHER', 'Other'), ('HEAVY', 'HEAVY'), ('SCOOTY&CAR', 'SCOOTY & CAR')], max_length=10),
        ),
    ]
